name: Run Page Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Set this to your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt file

      - name: Run page generator
        run: |
          python page_generator.py  # Use the relative path to your script
